# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e583878ebb42918a5938af220f4841aa74024028929b7f12b030e8e794202ccd4c44f20f52b61721e5f2854c48cde29eb26a67a0ff37b4052e79b864667ee7

test:
  secret_key_base: 1a5759caf4fe7eafcbca5fca664eba48e72a05a7797f09edd0de153753cb60a8bc329df368a604db9d7636f19c8e1b6a1f3ef3eb029f26727d1e6f5dca0d4472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
